### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rambalachandran** [handrew/browserpilot#10]
Hello, this looks like a really nice tool and I would love to test it as part of my work but it doesnt have a license. Do you plan to release it under a business friendly license (Apache, BSD, MIT)?

**Comment by handrew** [comment]
Ah, I never got around to it. I'll upload an MIT license soon.

**Comment by handrew** [comment]
Added. Go wild!

**Comment by rambalachandran** [comment]
Thank you
