### ISSUE TITLE
Open Table reservation instruction scenario

### ISSUE THREAD

**Issue by agn-7** [handrew/browserpilot#9]
could you please help me out regarding to provide an instruction in order to book a table on OpenTable.com with some extra information?

Here's the objective: "Book a table for a dinner at 10 PM, 09 Aprol 2024 for three people on Open Table website in London, and order any food with any budget, it doesn't matter."

Here's what I've done so far:

```yaml
instructions:
- BEGIN_FUNCTION book_dinner_table
- Go to OpenTable.com
- Wait 2 seconds.
- Find the search input for restaurant, location, or cuisine.
- Click on the search input field.
- Type London as location and press enter.
- Wait 2 seconds.
- Identify and click on a random restaurant from the search results.
- Wait 2 seconds.
- Find the reservation date picker input.
- Click on the date picker and select "April 09, 2024".
- Find the time slot dropdown or input.
- Select or type in the desired dinner time.
- Find the party size dropdown or input.
- Select or type in "8" for the number of guests.
- Locate and click on the "Find a Table" button or equivalent.
- Wait for the available tables to load.
- Choose an available table time slot if presented with options.
- Click on the button to finalize the booking, such as "Reserve" or "Complete Reservation".
- END_FUNCTION
- RUN_FUNCTION book_dinner_table
- Wait for 10 seconds.
```

**Comment by handrew** [comment]
Hi, in general, I don't think BrowserPilot is powerful enough to reliably and deterministically handle instructions like "Find the search input for restaurant, location, or cuisine". You should think of it more like coding than talking to a friend: so, I would recommend something like `Find the input element with placeholder "Location, Restaurant, or Cuisine"`. In other words, the more HTML you know, and the more specific instructions / tags you can provide, the better. 

There are ways to make BrowserPilot more powerful—either with more powerful models, a better representation of the DOM in the context window, or even with vision language models—but I think those approaches are outside of the scope of BrowserPilot. And there are plenty of great people working on them! 

Anyway, what line is it crashing at? I would go through each line and try to make it more specific, and then go from there.

**Comment by handrew** [comment]
@agn-7 Glad that helped. Do you know how to inspect element (right click the page and then click inspect element)? That's how I figured out what the tag was. 

Again, "a random restaurant from the search results" is not going to register for the language model since we don't pass the DOM in as information. I don't think I allow imports either, so the code that is generated will not be able to `import random`. You will need to specify a specific restaurant. In this case, I'd do something like "Get the div with the data-test attribute set to `restaurant-cards`". 

It's a bit awkward, I know...

**Comment by agn-7** [comment]
@handrew 
Ahh, I see. 

I thought we send DOM elements of pages on each stage! Because I saw `ask_llm_to_find_element()` method in which uses DOM inside. However, apparently, this method is rarely used by LLM-generated selenium code at the very first stage, and I couldn't see that on most of the compiled selenium codes. Isn't it?

**Comment by handrew** [comment]
Yes, you're right, `ask_llm_to_find_element` is the one that looks at the DOM. You can trigger that by saying in your instructions: "Ask LLM to find the..."

**Comment by handrew** [comment]
@agn-7 did that solve your problem? If so, I'll close the issue. Like I said, unfortunately it's more of an art than a science so it might take some playing around with to get working. 

Also—I haven't forgotten about your PR yet. Will get to it soon, thanks for your patiencE!

**Comment by agn-7** [comment]
@handrew 
Actually, I decided to not go further with this scenario . . .

Thank you very much for your support.
